# TASK #1: DEFINE SINGLE- AND MULTI-DIMENSIONAL NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
#pip install numpy
import numpy as np

# Let's define a one-dimensional array 


In [10]:
# Let's create a numpy array from the list "my_list"
my_list=[20,23,45,46,45]
my_list

[20, 23, 45, 46, 45]

In [11]:
my_numpy_array=np.array(my_list)
my_numpy_array

array([20, 23, 45, 46, 45])

In [12]:
type(my_numpy_array)


numpy.ndarray

In [13]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[3,2,2],[2,3,3]])
my_matrix

array([[3, 2, 2],
       [2, 3, 3]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [14]:
my_matrix=np.array([[3,7,9,3],[4,3,2,2]])
my_matrix

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE BUILT-IN METHODS AND FUNCTIONS OF NUMPY

In [15]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.52877336, 0.66308841, 0.71297484, 0.86924368, 0.9248534 ,
       0.17290587, 0.96166434, 0.05796569, 0.91440684, 0.48005423,
       0.80204735, 0.73494699, 0.96405104, 0.19793296, 0.20120707,
       0.28351977, 0.78209695, 0.83217547, 0.27346683, 0.08278694])

In [16]:
# you can create a matrix of random number as well
x = np.random.rand(3,3)
x

array([[0.49548791, 0.39360063, 0.1977927 ],
       [0.4252418 , 0.41545972, 0.59006927],
       [0.28936563, 0.04077128, 0.75847617]])

In [17]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1,50)
x

33

In [18]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1,100,16)
x

array([ 6,  7, 67, 22, 14, 90, 76, 48, 55, 29, 36, 62, 93, 31, 57, 69],
      dtype=int32)

In [19]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,30)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x


array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [21]:
# Matrix of ones
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Array of zeros
x = np.zeros((3,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input())
x
a = np.random.randint(0,a,10)
a

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [24]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Add 2 numpy arrays together
sum = x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
sq1 = x**2
sq1

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [28]:
sqrt = np.sqrt(sq1)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [29]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, add the squares of respective elements of the two arrays:

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [4]:
import numpy as np

X = np.array([5,7,20])
Y = np.array([9,15,4])

sum_of_squares = X**2 + Y**2
sum_of_squares

array([106, 274, 416])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [31]:
arr = np.array([2,2,4,5,67,7,8,8])
arr

array([ 2,  2,  4,  5, 67,  7,  8,  8])

In [32]:
# Access specific index from the numpy array
arr[-1]

np.int64(8)

In [33]:
# Starting from the first index 0 up until and NOT including the last element
arr[0:3]

array([2, 2, 4])

In [34]:
# Broadcasting, altering several values in a numpy array at once
arr[2:6] = 0
arr

array([2, 2, 0, 0, 0, 0, 8, 8])

In [35]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10,(4,4))
matrix

array([[5, 5, 4, 8],
       [4, 7, 7, 4],
       [1, 9, 6, 3],
       [9, 2, 6, 3]], dtype=int32)

In [36]:
# Get a row from a mtrix
matrix[-1]

array([9, 2, 6, 3], dtype=int32)

In [37]:
# Get one element
matrix[0][2]

np.int32(4)

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [38]:
X = np.array([[2, 30, 20, -2 ,-4],
    [3, 4 , 40 ,-3 ,-2],
    [-3, 4 ,-6 ,90, 10],
    [25, 45, 34, 22, 12],
    [13, 24 ,22 ,32 ,37]])
X
X[-1] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [39]:
matrix = np.random.randint(1,10,(5,5))
matrix

array([[6, 4, 4, 6, 1],
       [4, 6, 1, 4, 4],
       [1, 9, 8, 2, 8],
       [3, 8, 9, 4, 4],
       [4, 5, 8, 8, 1]], dtype=int32)

In [40]:
new_matrix=matrix[matrix >7]
new_matrix

array([9, 8, 8, 8, 9, 8, 8], dtype=int32)

In [41]:
# Obtain odd elements only
new_matrix = matrix[matrix %2 == 1]
new_matrix

array([1, 1, 1, 9, 3, 9, 5, 1], dtype=int32)

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [42]:
X = np.array([[2 ,30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6 ,90 ,10],
    [25, 45, 34, 22, 12],
    [13 ,24, 22, 32, 37]])
X
X[X <0] = 0
X
X[X%2==1]=-2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as a spreadsheet in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.
#!pip install pandas

In [5]:
import pandas as pd

In [50]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client_df=pd.DataFrame({
    'Bank Client ID':[111,222,333,444],
    'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
    'Net Worth':[3500,2300,3400,2200]
})
bank_client_df

Bank Client ID Bank Client Name  Net Worth
0             111           Chanel       3500
1             222            Steve       2300
2             333            Mitch       3400
3             444             Ryan       2200

In [51]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [52]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net Worth
0             111           Chanel       3500
1             222            Steve       2300

In [53]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth
2             333            Mitch       3400
3             444             Ryan       2200

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [54]:
stocks_df=pd.DataFrame({
    'SYM': ['APPL','BANAN','DDD'],
    'Number of Shares':[100,20,44],
    'Price per Share':[10,20,10]
})
stocks_df


SYM  Number of Shares  Price per Share
0   APPL               100               10
1  BANAN                20               20
2    DDD                44               10

In [55]:
val = stocks_df['Price per Share'] * stocks_df['Number of Shares']
val.sum()

np.int64(1840)

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [6]:
# Pandas is used to read a csv file and store data in a DataFrame
!python -m pip install --upgrade pip
!pip install lxml

house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

DEPRECATION: Loading egg at c:\users\rishi\downloads\installed\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\rishi\downloads\installed\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330


City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [7]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [ ]:
# Read tabular data using read_html


MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [8]:
retirement_df=pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [57]:
# Let's define a dataframe as follows:
bank_client_df=pd.DataFrame({
    'Bank Client ID':[111,222,333,444],
    'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
    'Net Worth':[3500,23000,34000,2200],
    'Years with Bank':[3,4,9,5]
})
bank_client_df

Bank Client ID Bank Client Name  Net Worth  Years with Bank
0             111           Chanel       3500                3
1             222            Steve      23000                4
2             333            Mitch      34000                9
3             444             Ryan       2200                5

In [58]:
# Pick certain rows that satisfy a certain criteria 
loyal= bank_client_df[bank_client_df['Years with Bank']>=5]
loyal

Bank Client ID Bank Client Name  Net Worth  Years with Bank
2             333            Mitch      34000                9
3             444             Ryan       2200                5

In [59]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

Bank Client Name  Net Worth  Years with Bank
0           Chanel       3500                3
1            Steve      23000                4
2            Mitch      34000                9
3             Ryan       2200                5

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [61]:
hni=bank_client_df[ bank_client_df['Net Worth']>=5000]
hni

hni['Net Worth'].sum()

np.int64(57000)

# TASK #9: PANDAS WITH FUNCTIONS

In [62]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [63]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def network_update(balance):
    return balance * 1.2

In [64]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(network_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [65]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [66]:
stocks_df=pd.DataFrame({
    'SYM': ['APPL','BANAN','DDD'],
    'Number of Shares':[100,20,44],
    'Price per Share':[10,20,10]
})
stocks_df

def increment(balance):
    return balance*3 + 200
stocks_df['Price per Share'].apply(increment)


0    230
1    260
2    230
Name: Price per Share, dtype: int64

In [67]:
stocks_df

SYM  Number of Shares  Price per Share
0   APPL               100               10
1  BANAN                20               20
2    DDD                44               10

In [68]:
result= bank_client_df['Net worth [$]'].apply(increment)
result.sum()

np.int64(134300)

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [69]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [70]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by='Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [71]:
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [72]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df.sort_values(by='Years with bank',inplace=True)
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [ ]:
# Set inplace = True to ensure that change has taken place in memory 


In [ ]:
# Note that now the change (ordering) took place 


# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html


In [73]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)

In [74]:
df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)


In [75]:
df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[8, 9, 10, 11],
)


In [76]:
frames = [df1,df2,df3]

In [77]:
result = pd.concat(frames)
result

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11